DROP TABLE IF EXISTS CLIENTES;

CREATE TABLE  "CLIENTES" (
    "DNI" VARCHAR2(9) IDENTITY PRIMARY KEY,
	"NOMBRE" VARCHAR2(40) NOT NULL,
    "APELLIDOS" VARCHAR2(80) NOT NULL,
    "CORREO" VARCHAR2(100) NOT NULL,
	"TELEFONO" NUMBER NOT NULL,
);