DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE  "CLIENTE" (
    "ID" INTEGER IDENTITY PRIMARY KEY,
    "DNI" VARCHAR2(20) NOT NULL,
	"NOMBRE" VARCHAR2(40) NOT NULL,
    "APELLIDOS" VARCHAR2(80) NOT NULL, 
	"TELEFONO" NUMBER,
    "CORREO" VARCHAR2(100) NOT NULL
);



CREATE TABLE "TRATAMIENTO" (
    "ID" INTEGER IDENTITY PRIMARY KEY,
    "NOMBRE" VARCHAR2(40) NOT NULL,
    "PRECIO" NUMBER,
    "DURACION" TIME NOT NULL,
    "DESCRIPCION" VARCHAR2(100) NOT NULL
);


CREATE TABLE "HISTORIAL" (
    "ID" INTEGER IDENTITY PRIMARY KEY,
    "DNI" VARCHAR2(20) NOT NULL,
    "ID_TRATAMIENTO" VARCHAR2(20) NOT NULL,
    "DATE" DATE NOT NULL,
    "TIME" TIME NOT NULL
)